name: APK para crear usuarios de redes sociales

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    name: construir
    runs-on: ubuntu-latest

    steps:
      - name: Descargar proyecto
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Se utiliza la acción oficial de Gradle que descarga el SDK automáticamente sin romperse
      - name: Configurar Gradle y SDK de Android
        uses: gradle/actions/setup-gradle@v4

      - name: Conceder permisos de ejecución a gradlew
        run: chmod +x ./gradlew
        working-directory: ./app

      - name: Compilar APK de lanzamiento (Release)
        run: ./gradlew assembleRelease --stacktrace
        working-directory: ./app

      - name: Guardar APK como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: Social-Swingers-APK
          path: "app/build/outputs/apk/release/*.apk"
