      - name: Conceder permisos de ejecución a gradlew
        run: chmod +x ./gradlew
        working-directory: ./app

      - name: Compilador APK de lanzamiento (Versión)
        run: ./gradlew assembleRelease --stacktrace
        working-directory: ./app
